apiVersion: v1
kind: Service
metadata:
  name: takserver-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: takserver-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: takserver-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: takserver-db
  template:
    metadata:
      labels:
        app: takserver-db
    spec:
      containers:
        - name: takserver-db
          image: immauss/tak-db:25.02.04
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: takserver-secret
                  key: TAK_DB_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: takserver-db-storage
      volumes:
        - name: takserver-db-storage
          persistentVolumeClaim:
            claimName: takserver-db-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: takserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: takserver
  template:
    metadata:
      labels:
        app: takserver
    spec:
      containers:
        - name: takserver
          image: immauss/tak-tak:25.02.04
          env:
            - name: envpass
              valueFrom:
                secretKeyRef:
                  name: takserver-secret
                  key: TAK_DB_PASSWORD
            - name: DB_HOST
              value: "takserver-db"
            - name: STATE
              value: "NSS"
            - name: CITY
              value: "NSC"
            - name: ORGANIZATION
              value: "NSO"
            - name: ORGANIZATIONAL_UNIT
              value: "NSOU"
          ports:
            - containerPort: 8443
            - containerPort: 8444
            - containerPort: 8446
            - containerPort: 8089
            - containerPort: 9001
          volumeMounts:
            - mountPath: /opt/tak/certs/files
              name: takserver-storage
      volumes:
        - name: takserver-storage
          persistentVolumeClaim:
            claimName: takserver-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: takserver-service
spec:
  type: NodePort
  ports:
    - port: 8443
      targetPort: 8443
      nodePort: 30443
      name: port-8443
    - port: 8444
      targetPort: 8444
      nodePort: 30444
      name: port-8444
    - port: 8446
      targetPort: 8446
      nodePort: 30446
      name: port-8446
    - port: 8089
      targetPort: 8089
      nodePort: 30089
      name: port-8089
    - port: 9001
      targetPort: 9001
      nodePort: 31001
      name: port-9001 
  selector:
    app: takserver
