apiVersion: v1
kind: Service
metadata:
  name: takserver-db
  namespace: tak
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: takserver-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: takserver-db
  namespace: tak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: takserver-db
  template:
    metadata:
      labels:
        app: takserver-db
    spec:
      containers:
        - name: takserver-db
          image: immauss/tak-db:25.02.09
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: tak-db-storage
            - mountPath: /opt/tak/configs
              name: tak-configs
      volumes:
        - name: tak-db-storage
          persistentVolumeClaim:
            claimName: tak-db-pvc
        - name: tak-configs
          persistentVolumeClaim:
            claimName: tak-configs-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: takserver
  namespace: tak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: takserver
  template:
    metadata:
      labels:
        app: takserver
    spec:
      containers:
        - name: takserver
          image: immauss/tak-tak:25.02.09
          env:
            - name: PUBLIC_FQDN
              value: "mpetak.2cr.army.mil"
            - name: DB_HOST
              value: "takserver-db"
            - name: STATE
              value: "NSS"
            - name: CITY
              value: "NSC"
            - name: ORGANIZATION
              value: "NSO"
            - name: ORGANIZATIONAL_UNIT
              value: "NSOU"
          ports:
            - containerPort: 8443
            - containerPort: 8444
            - containerPort: 8446
            - containerPort: 8089
            - containerPort: 9001
          volumeMounts:
            - mountPath: /opt/tak/certs/files
              name: tak-certs
            - mountPath: /opt/tak/configs
              name: tak-configs
      volumes:
        - name: tak-certs
          persistentVolumeClaim:
            claimName: tak-certs-pvc
        - name: tak-configs
          persistentVolumeClaim:
            claimName: tak-configs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: takserver-service
  namespace: tak
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  selector:
    app: takserver
  ports:
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: port-8443
    - port: 8444
      targetPort: 8444
      protocol: TCP
      name: port-8444
    - port: 8446
      targetPort: 8446
      protocol: TCP
      name: port-8446
    - port: 8089
      targetPort: 8089
      protocol: TCP
      name: port-8089
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: port-9001 
  selector:
    app: takserver
