apiVersion: v1
kind: PersistentVolume
metadata:
  name: takserver-pv-local-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "STORAGEPATH/db"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: takserver-pv-local-2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "STORAGEPATH/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: takdb-pvc-local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: takdata-pvc-local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
