apiVersion: v1
kind: PersistentVolume
metadata:
  name: takserver-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: s3-bucket
  csi:
    driver: s3.csi.k8s.io
    volumeHandle: takserver-s3
    volumeAttributes:
      bucketName: takserver-data-bucket
      region: us-east-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: takserver-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: s3-bucket
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: takserver-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: takserver-db
  template:
    metadata:
      labels:
        app: takserver-db
    spec:
      containers:
        - name: takserver-db
          image: immauss/tak-db:25.02.03
          env:
            - name: envpass
              valueFrom:
                secretKeyRef:
                  name: takserver-secret
                  key: TAK_DB_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: takserver-storage
      volumes:
        - name: takserver-storage
          persistentVolumeClaim:
            claimName: takserver-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: takserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: takserver
  template:
    metadata:
      labels:
        app: takserver
    spec:
      containers:
        - name: takserver
          image: immauss/tak-tak:25.02.03
          env:
            - name: envpass
              valueFrom:
                secretKeyRef:
                  name: takserver-secret
                  key: TAK_DB_PASSWORD
            - name: STATE
              value: "NSS"
            - name: CITY
              value: "NSC"
            - name: ORGANIZATION
              value: "NSO"
            - name: ORGANIZATIONAL_UNIT
              value: "NSOU"
          ports:
            - containerPort: 8080
            - containerPort: 8443
            - containerPort: 8444
            - containerPort: 8446
            - containerPort: 8087
            - containerPort: 8088
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - mountPath: /opt/tak
              name: takserver-storage
      volumes:
        - name: takserver-storage
          persistentVolumeClaim:
            claimName: takserver-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: takserver-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
    - port: 8443
      targetPort: 8443
    - port: 8444
      targetPort: 8444
    - port: 8446
      targetPort: 8446
    - port: 8087
      targetPort: 8087
    - port: 8088
      targetPort: 8088
    - port: 9000
      targetPort: 9000
    - port: 9001
      targetPort: 9001
  selector:
    app: takserver
