FROM registry1.dso.mil/ironbank/tpc/tak/tak-server:latest
# put updated start script in user home directory
RUN mkdir /home/tak/scripts
COPY ./start.sh /home/tak/scripts/start.sh
LABEL maintainer="george.e.knauss.ctr@army.mil" \
      version="25.02.01" \
      description="TAK server from Iron Bank with custom start script"
ENTRYPOINT ["/bin/bash","/home/tak/scripts/start.sh"]